language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

install: true

os:
  - linux

sudo: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: site
  email: vadzim.kavalkou@gmail.com
  name: Vadzim Kavalkou
  on:
    branch: master

notifications:
  email:
    recipients:
      - vadzim.kavalkou@gmail.com
    on_success: never
    on_failure: always

branches:
  only:
    - master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew build

after_success:
  - ./gradlew jacocoTestReport coveralls
  - ./gradlew javadoc