version: '3.7'
services:
  api:
    container_name: api
    image: "fragaly/booking-system"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost || exit 1"]
      interval: 30m
      timeout: 10s
      retries: 3
      start_period: 2m
    restart: always
    expose:
      - 8080
    ports:
      - 8080:8080
    #todo vk: use stack to work with swarm
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.05'
          memory: 128M
      replicas: 3