version: '3'
services:
  api:
    container_name: api
    restart: always
    image: "fragaly/booking-system"
    expose:
      - 8080
    ports:
      - 8080:8080
    #todo vk: use stack to work with swarm
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.05'
          memory: 128M
      replicas: 3