version: "3.7"

services:

  #api service
  api:
    container_name: api
    image: "fragaly/booking-system"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080 || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    restart: always
    expose:
      - 8080
    ports:
      - 8080:8080

  #cadvisor service
  monitoring:
    container_name: monitoring
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

    restart: always
    expose:
      - 8081
    ports:
      - 8081:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/containers/ || exit 1"]
      interval: 10m
      timeout: 10s
      retries: 3
      start_period: 1m

  #elk
  elk:
    container_name: elk
    image: sebp/elk
    restart: always
    expose:
      - 8082
    ports:
      - 5601:5601 #kibana port
      - 9200:9200 #elasticsearch port
      - 5044:5044 #logstash port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601 || exit 1"]
      interval: 10m
      timeout: 10s
      retries: 3
      start_period: 1m