spring:
  profiles:
    active: "development"
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: "/swagger*"
  data:
    mongodb:
      database: "booking-system"
      uri: "mongodb+srv://developer:Password@booking-system-0-hmiup.mongodb.net/booking-system?streamType=netty&maxPoolSize=75&minPoolSize=0&maxIdleTimeMS=10000&connectTimeoutMS=60000&retryWrites=true"
  jackson:
    serialization:
      indent_output: true
      write-dates-as-timestamps: false
    mapper:
      accept_case_insensitive_enums: true
    parser:
      allow_comments: true
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
    time-zone: "UTC"
  resources:
    cache:
      cachecontrol:
        max-age: 3600
        must-revalidate: true
        cache-private: true
        cache-public: false
  banner:
    location: banner/api-banner.txt
    charset: UTF-8
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 50MB

logging:
  pattern:
    console: "%cyan(%date{\"yyyy-MM-dd'T'HH:mm:ss,SSSXXX\", UTC}) %red(UTC) - [%yellow(%msg)]%n"
    file: "%date{\"yyyy-MM-dd'T'HH:mm:ss,SSSXXX\", UTC} UTC [%thread] %-5level %logger{36} - %msg%n"
    dateformat:
    level: "%5p"

server:
  port: 8888
  jetty:
    acceptors: -1
    selectors: -1
  servlet:
    context-path: /api
    session:
      timeout: 3600
    compression:
      enabled: true
      mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json"
      min-response-size: 1024
    http2:
      enabled: true
  error:
    include-stacktrace: always
    whitelabel:
      enabled: false