spring:
  profiles:
    active: "development"
  main:
    banner-mode: "off"

logging:
  level:
    ROOT: DEBUG
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG

server:
  port: 8080