spring:
  main:
    banner-mode: "off"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: booking-system
      uri: mongodb://localhost/booking-system
      #username:
      #password:
      repositories:
        type: "auto"

logging:
  level:
    ROOT: DEBUG
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG

server:
  port: 8080