spring:
  main:
    banner-mode: "off"
  #data:
    #mongodb:
      #host: localhost
      #port: 27017
      #database: booking-system
      #username:
      #password:
    #devtools:
    #add-properties: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG

server:
  port: 8080
