spring:
  profiles:
    active: "development"
  mvc:
    throw-exception-if-no-handler-found: true
  data:
    mongodb:
      database: "booking-system"
      uri: "mongodb+srv://developer:Password@development-hmiup.mongodb.net/booking-system?retryWrites=true"
  jackson:
    serialization:
      indent_output: true
      write-dates-as-timestamps: false
    mapper:
      accept_case_insensitive_enums: true
    parser:
      allow_comments: true
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
    time-zone: "UTC"
  resources:
    cache:
      cachecontrol:
        max-age: 120
        must-revalidate: true
        cache-private: true
        cache-public: false
  banner:
    location: banner/api-banner.txt

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      timeout: 3600
    compression:
      enabled: true
      mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json"
      min-response-size: 512
    http2:
      enabled: true
    tomcat:
      max-threads: 0
      uri-encoding: "UTF-8"
  error:
    include-stacktrace: always
    whitelabel:
      enabled: false