spring:
  profiles:
    active: "development"
  main:
    banner-mode: "off"
  data:
    mongodb:
      database: "booking-system"
      uri: "mongodb+srv://developer:developerPassword@development-hmiup.mongodb.net/booking-system?retryWrites=true"
  jackson:
    mapper:
      accept_case_insensitive_enums: true
    parser:
      allow_comments: true

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    guru.springframework.controllers: INFO

server:
  port: 8080