apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-system
spec:
  replicas: 3
  selector:
    matchlabels:
      app: booking-system
  template:
    metadata:
      labels:
        app: booking-system
    spec:
      containers:
        - name: booking-system
          image: fragaly/booking-system
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: "http"
            - containerPort: 5005
              name: "debug"