apiVersion: v1
kind: Service
metadata:
  name: booking-system
spec:
  selector:
    matchlabels:
      app: booking-system
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
